global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ad-optimizer"
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "app:8000"
